name: Daily AI Commit

on:
  schedule:
    - cron: '30 3 * * *'    # 9:00 AM IST (03:30 UTC)
    - cron: '30 12 * * *'   # 6:00 PM IST (12:30 UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Generate AI Content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "## Daily Cybersecurity Note 🚀" > ai_content.md
          echo "" >> ai_content.md
          python - <<EOF
import os
from datetime import datetime, timezone
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

prompt = "Give me one short but useful cybersecurity tip or fact in 2-3 sentences. Keep it professional."

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": prompt}],
    max_tokens=80,
    temperature=0.7
)

fact = f"### {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n\n"
fact += response.choices[0].message.content.strip()

with open("ai_content.md", "a") as f:
    f.write("\n\n" + fact)
EOF

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ai_content.md
          git commit -m "chore: update daily AI content"
          git push
